### ISSUE TITLE
10.24까지 todo

### ISSUE THREAD

**Issue by gpwltl** [TeamTMTB/TMTB#9]
📌 10.24 제출할 것 
- 보강 기획서
- 요구사항 정리 (user story/ back log 등)
- 기능 명세/ 설계
- 일정 계획 WBS 
- 초기 아키텍처 설계

<br />

📌 10.10~10.17 할 일
- [x] 협업 툴 정하기(freedcamp, slack 등)

- [ ] 요구사항 정리

- [ ] 개발 방법 정리 

- [ ] WBS(일정) 정하기 (너무 구체적이지 않더라도 형태 정도)

- [x] 보강 기획서 
- 다른 조꺼 참고해서 목차 추가
- 유저 타겟팅 정의 (유저케이스 설계) -> 기능을 위해서라도 **구체화 필요**
(예. 자격증 준비생, 공무원 준비생 등 -> 누가 어떤 시스템을 사용할건지)
- 스터디카페, 학원(오프라인)쪽으로 확장되어 생각해볼 것 -> 주 메인 서비스는 온라인 스터디를 하되 오프라인이랑 연계하면 상품성이 더 높아짐
